name: flare_skeleton_example
description: Example app for flare_skeleton package.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flare_skeleton:
    path: ../

flutter:
  uses-material-design: true
